In [23]:
"""
Colab & HF setup
- mount GDrive (store your access tokens there if ever)
- authenticate GitHub
- authenticate HuggingFace

If you're not on Colab, you can skip this.
If you're on Colab, run this once per runtime.
"""

!git clone https://github.com/Pacozabala/CSCI199.X-workbench
%cd CSCI199.X-workbench

from google.colab import drive
drive.mount('/content/drive')

with open("/content/drive/MyDrive/keys/ghpat-colab.txt") as f:
  GH_TOKEN = f.read().strip()

import os, subprocess
REPO_URL = "https://github.com/Pacozabala/CSCI199.X-workbench"
GH_USER = os.environ["GH_USER"]

auth_url = REPO_URL.replace(
    "https://",
    f"https://{GH_USER}:{GH_TOKEN}@"
)
subprocess.run(["git", "remote", "set-url", "origin", auth_url], check=True)


with open("/content/drive/MyDrive/keys/hfpat-colab.txt") as f:
  HF_TOKEN = f.read().strip()

from huggingface_hub import login
login(token=HF_TOKEN)

Cloning into 'CSCI199.X-workbench'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 164 (delta 93), reused 117 (delta 51), pack-reused 0 (from 0)
Receiving objects: 100% (164/164), 5.60 MiB | 14.15 MiB/s, done.
Resolving deltas: 100% (93/93), done.
/content/CSCI199.X-workbench/CSCI199.X-workbench/CSCI199.X-workbench/CSCI199.X-workbench/CSCI199.X-workbench
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Flat-classification with MoralBERT

MoralBERT is specified as such:
- ADAM optimizer is used with a learning rate of $5e^{-5}$
- there are $16$ batch sizes and $5$ epochs.

In this notebook MoralBERT is fine-tuned on our augmented MFRC. The lexically polarity-annotated MFRC is one hot encoded with respect to the five moral foundations. After this MoralBERT is bulk loaded and fine-tuned.

In [24]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/datasets/MFRC_polarity_pacoscript.csv")
df = df.dropna(subset=["polarity"])
df.head()

,text,subreddit,bucket,annotator,annotation,confidence,polarity
4,The Le Pen brand of conservatism and classical...,europe,French politics,annotator03,Authority,Somewhat Confident,authority.virtue
12,You are simplifying it. Islam is not the sole ...,europe,French politics,annotator03,Harm,Confident,harm.vice
13,You are simplifying it. Islam is not the sole ...,europe,French politics,annotator01,"Ingroup,Harm",Confident,"ingroup.vice,harm.vice"
14,You are simplifying it. Islam is not the sole ...,europe,French politics,annotator02,Harm,Confident,harm.vice
19,&gt; Valls is such a disgusting traitor to his...,europe,French politics,annotator04,"Ingroup,Purity,Authority",Confident,purity.vice

In [25]:
mfrc_ohe = df[["text", "polarity"]].copy()
mfrc_ohe.head()

                                                 text                polarity
4   The Le Pen brand of conservatism and classical...        authority.virtue
12  You are simplifying it. Islam is not the sole ...               harm.vice
13  You are simplifying it. Islam is not the sole ...  ingroup.vice,harm.vice
14  You are simplifying it. Islam is not the sole ...               harm.vice
19  &gt; Valls is such a disgusting traitor to his...             purity.vice

In [26]:
labels = [
    "harm.virtue",
     "harm.vice",
     "authority.virtue",
     "authority.vice",
     "fairness.virtue",
     "fairness.vice",
     "loyalty.virtue",
     "loyalty.vice",
     "purity.virtue",
     "purity.vice"
     ]

for label in labels:
  mfrc_ohe[label] = 0


mfrc_ohe['polarity'] = mfrc_ohe['polarity'].str.replace('ingroup', 'loyalty', regex=False)
mfrc_ohe.head()

,text,polarity,harm.virtue,harm.vice,authority.virtue,authority.vice,fairness.virtue,fairness.vice,loyalty.virtue,loyalty.vice,purity.virtue,purity.vice
4,The Le Pen brand of conservatism and classical...,authority.virtue,0,0,0,0,0,0,0,0,0,0
12,You are simplifying it. Islam is not the sole ...,harm.vice,0,0,0,0,0,0,0,0,0,0
13,You are simplifying it. Islam is not the sole ...,"loyalty.vice,harm.vice",0,0,0,0,0,0,0,0,0,0
14,You are simplifying it. Islam is not the sole ...,harm.vice,0,0,0,0,0,0,0,0,0,0
19,&gt; Valls is such a disgusting traitor to his...,purity.vice,0,0,0,0,0,0,0,0,0,0

In [27]:
dummies = mfrc_ohe['polarity'].str.get_dummies(sep=',')
mfrc_ohe.update(dummies)
mfrc_ohe.head()

,text,polarity,harm.virtue,harm.vice,authority.virtue,authority.vice,fairness.virtue,fairness.vice,loyalty.virtue,loyalty.vice,purity.virtue,purity.vice
4,The Le Pen brand of conservatism and classical...,authority.virtue,0,0,1,0,0,0,0,0,0,0
12,You are simplifying it. Islam is not the sole ...,harm.vice,0,1,0,0,0,0,0,0,0,0
13,You are simplifying it. Islam is not the sole ...,"loyalty.vice,harm.vice",0,1,0,0,0,0,0,1,0,0
14,You are simplifying it. Islam is not the sole ...,harm.vice,0,1,0,0,0,0,0,0,0,0
19,&gt; Valls is such a disgusting traitor to his...,purity.vice,0,0,0,0,0,0,0,0,0,1

In [44]:
!cp /content/drive/MyDrive/Colab\ Notebooks/single-label-classifiers.ipynb .
!git add

commit 535687de68bc581897910e6b95f07d7562fe4c27 (HEAD -> max/single-label-classifiers-approach, origin/max/single-label-classifiers-approach)
Author: jeanmaxcacacho <maxcacacho@gmail.com>
Date:   Sat Feb 28 01:06:04 2026 +0000

    chore: include github authentication in colab setup cell

commit 9e6ca37faf84f811f361bd09fc386a8b70dc35e5
Author: jeanmaxcacacho <maxcacacho@gmail.com>
Date:   Fri Feb 27 08:36:58 2026 +0000

    chore: colab and HF setup in notebook, 'load' roberta-base

commit 9ca06f917289f7ad494b970030d694ab39179d56
Author: jeanmaxcacacho <maxcacacho@gmail.com>
Date:   Fri Feb 27 07:57:08 2026 +0000

    feat: init single label classifiers notebook

commit 01bb2958d747f051284c8faced142f8b13bac87d
Author: Paco Antonio Zabala <157790408+Pacozabala@users.noreply.github.com>
Date:   Fri Feb 27 15:26:47 2026 +0800

    3 epochs training

commit 2160023dc4ec43e50d65707d534b18c00c08fee0
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Thu Feb 26 18:30:16 2026 +0800

    finally documented README.md

commit fbef582284aefacf95adb0ed0988f705da52b7c2
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Thu Feb 26 13:17:24 2026 +0800

    feat: added CL args to roberta training script

commit 97d5474c530fd1b4aec849b8ad676248defc32a7
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Thu Feb 26 12:20:17 2026 +0800

    modified some inconsistencies in bow

commit 500c1b3f572c34c0fb5e890df3042e675c8490d6
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Thu Feb 26 11:28:15 2026 +0800

    fixed bow typos

commit c8d3c6c305c255776e8610dafdc2ed079e05b6c6
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Thu Feb 26 11:23:07 2026 +0800

    changed bow output path

commit 5f5d1bf994e556981c682c9001cf606d1ed467c7
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Sat Feb 21 23:03:35 2026 +0800

    typo in bow labeler

commit 876f48df17f5ac18df4bc925e187c6368aba72e8
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Fri Feb 20 20:41:30 2026 +0800

    feat: bow label options for lemma and tie-breaking

commit 6207f1cb2147310645483d96f4f7e644efd297b0
Merge: 00d8169 fae4129
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Fri Feb 20 20:02:13 2026 +0800

    Merge branch 'main' of https://github.com/Pacozabala/CSCI199.X-workbench

commit 00d816995c5a56ae15e6bc8ce4d3f845c0035656
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Fri Feb 20 20:01:36 2026 +0800

    feat: bow polarity labelling module

commit fae4129981c6d12e44fc475dd7819a7c4a25aa6a
Author: Paco Antonio Zabala <157790408+Pacozabala@users.noreply.github.com>
Date:   Thu Feb 19 16:07:03 2026 +0800

    Created using Colab

commit d2ad2535e878a8af1f4cb34368b0435c756032fa
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Thu Feb 19 14:53:23 2026 +0800

    increased epochs

commit 87738205b5264a0a3b10f346a5ec1e61434bd73e
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 22:26:00 2026 +0800

    fix: training script's evaluate function

commit 33a5e15272b9079a293b0950b40aa2f1b3005d89
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 21:57:39 2026 +0800

    fix: training read paths

commit b4a20b77242266d8892ef555a332340f444f5a76
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 21:55:43 2026 +0800

    fix: train_roberta imports

commit c3f457df5b34ecffd9472698c2b00f650752d24e
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 20:17:26 2026 +0800

    feat: training script for 1 classifier

commit 309dd3917b050c77306d43c99f6cb09306341a2a
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 20:13:51 2026 +0800

    feat: training script for 1 classifier

commit 2db243414b7bfd150e78a79aa103da3b910b34e5
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 19:14:40 2026 +0800

    chore:changed filename of dataset prep module

commit fe707d088164dbc4461ccfe07c794d5664739038
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 18:02:33 2026 +0800

    fix: split_csv.py paths

commit 1c1f0caee66de745f6a12fa86586bf01d18d3386
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 17:47:38 2026 +0800

    feat: split.csv now accpets CL args

commit 026960c33768dc3a3af438260347f42fbbb64ebf
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Wed Feb 18 17:24:04 2026 +0800

    feat: csv cleaning and splitting script

commit 78c373c7d6c35ab9fb53cf59f40e7e672875c446
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Tue Feb 17 20:16:17 2026 +0800

    chore: added polarity-labeled dataset

commit 1ba706c24b81ff24e2acdbe90834e29e3e0243f3
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Tue Feb 17 19:46:47 2026 +0800

    chore: added lexicons and MFRC to data folder

commit 4c4576c96cc2b20d344246ff18c6e48a98218d8e
Author: Paco Antonio Zabala <paco.zabala@student.ateneo.edu>
Date:   Tue Feb 17 19:43:18 2026 +0800

    chore: updated .gitignore for working files

commit 109d908a78a37059ed3fa4a6ae560e6715087941
Author: Paco Antonio Zabala <157790408+Pacozabala@users.noreply.github.com>
Date:   Mon Feb 16 21:43:14 2026 +0800

    Initial commit